version: '3.7'

services:

  config-server:
    container_name: config-server
    image: vilastarte/config-server:latest
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - currency-network

  naming-server:
    container_name: naming-server
    image: vilastarte/naming-server:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
    depends_on:
      - config-server
      
  sal-service:
    container_name: sal-service
    image: vilastarte/sal-service:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'

  api-gateway:
    container_name: api-gateway
    image: vilastarte/api-gateway:latest
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'
 
  day-service:
    container_name: day-service
    image: vilastarte/day-service:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'
  
  advance-service:
    container_name: advance-service
    image: vilastarte/advance-service:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
       SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://naming-server:8761/eureka"}}}}'


networks:
  currency-network: